- hosts: tag_role_proxy
  become: yes
  vars:
   ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q centos@haproxy.projecteka.in"'
   ansible_user: centos
  roles:
    - container-dns
  vars_files:
    - "vars/secrets.yml"
    - "vars/cidr_blocks.yml"
    - "vars/vars.yml"