version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.8.2-alpine"
    ports:
      - "5672:5672"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:rw"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:rw"
      - "./volumes/rabbitmq/rabbit1/data:/var/lib/rabbitmq:rw"