apiVersion: v1
kind: Namespace
metadata:
  name: consent-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-dev
  namespace: consent-manager
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: rabbitmq-dev
      version: 'v1'
  template:
    metadata:
      labels:
        app: rabbitmq-dev
        version: 'v1'
    spec:
      containers:
        - name: rabbitmq-dev
          image: devinfysurveyappregistry.azurecr.io/rabbitmq:latest
          ports:
              - containerPort: 5672
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "sleep 30; rabbitmqctl import_definitions /tmp/definitions.json"]

