---

- name: get Security group info
  command: "aws ec2 describe-security-groups --region {{ aws_region }}"
  register: get_security_group_info
  changed_when: false

- set_fact:
    securityGroup: "{{ get_security_group_info.stdout|from_json }}"
  tags: fetchvpc

- name: Populate SecurityGroupIds
  set_fact:
    SecurityGroupIds: "{{ lookup('template', 'security_group.j2') }}"
  vars:
    securityGroups: "{{ securityGroup.SecurityGroups }}"

- name: Gather EC2 info.
  ec2_instance_info:
    aws_secret_key: "{{ aws_secret_key  }}"
    aws_access_key: "{{ aws_access_key }}"
    region: "{{ aws_region }}"
  register: ec2_facts
