---
- name: Add Docker
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644

- name: Configure Docker repo
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}-edge'
    option: enabled
    value: '{{ docker_yum_repo_enable_edge }}'

- name: Install Docker
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Docker is started and enabled at boot
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Docker users are added to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_users }}"
  
- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755

- name: Copy docker_hook and set permission
  copy:
    src: docker_hook
    dest: /home/centos/docker_hook
    owner: centos
    group: centos
    mode: '0755'

- name: Copy deployment script and set permission
  copy:
    src: deploy.sh
    dest: /home/centos/deploy.sh
    owner: centos
    group: centos
    mode: '0755'

- name: Copy docker hook startup script
  become: yes
  template:
      src: hook_startup.j2
      dest: /home/centos/hook_startup.sh
      mode: '755'

- name: Copy dockerhook_service and set permission
  copy:
    src: dockerhook.service
    dest: /etc/systemd/system/dockerhook.service
    owner: root
    group: root
    mode: '0755'
  notify: reload systemd
    
- name: Docker_hook is started and enabled at boot
  service:
    name: dockerhook
    enabled: yes
    state: started